# Generated by Django 5.2.8 on 2025-11-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemonentity_damage_pokemonentity_defence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='appeared_at',
            new_name='appeares_at',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='disappeared_at',
            new_name='disappeares_at',
        ),
    ]
